import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { api } from '../api';
import { haptic } from '../telegram';

export function DeFiScreen({ onClaim }: { onClaim: (id: string) => void }) {
  const [total, setTotal] = useState('10');
  const [count, setCount] = useState('5');
  const [groupId, setGroupId] = useState('');
  const [message, setMessage] = useState('');
  const mutation = useMutation({ mutationFn: () => api<{ envelope: { id: string } }>('/api/envelopes', { method: 'POST', body: JSON.stringify({ total, count: Number(count), groupId: groupId || '0', mode: 'RANDOM', expiresInMinutes: 1440 }) }), onSuccess: (data) => setMessage(`Envelope ${data.envelope.id.slice(0, 8)} created. Send the Telegram claim button in your group.`), onError: (error) => setMessage(error instanceof Error ? error.message : 'Unable to create envelope.') });
  return <main className="screen"><header className="topbar"><div><p className="eyebrow">COMMUNITY FINANCE</p><h1>DeFi & Red Envelopes</h1></div><span className="round-symbol">◈</span></header><section className="feature-banner"><div className="banner-orb">🧧</div><div><span className="eyebrow">TELEGRAM NATIVE</span><h2>Share a little luck.</h2><p>Turn your USDT balance into a fair, instant community moment.</p></div></section><section className="section create-card"><div className="section-heading"><div><h2>Create red envelope</h2><p className="muted">Funds are reserved atomically from your wallet.</p></div><span className="status-pill">RANDOM</span></div><div className="inline-fields"><label className="field-label">Total USDT<input inputMode="decimal" value={total} onChange={(event) => setTotal(event.target.value)} /></label><label className="field-label">Slots<input inputMode="numeric" value={count} onChange={(event) => setCount(event.target.value.replace(/\D/g, ''))} /></label></div><label className="field-label">Telegram group ID <span className="optional">optional</span><input placeholder="-100…" value={groupId} onChange={(event) => setGroupId(event.target.value)} /></label><button className="primary-button" disabled={mutation.isPending} onClick={() => { haptic('medium'); setMessage(''); mutation.mutate(); }}>{mutation.isPending ? 'Creating…' : 'Create envelope'}</button>{message && <div className={message.startsWith('Envelope') ? 'success-box' : 'error-box'}>{message}</div>}</section><section className="section"><div className="section-heading"><h2>Your claims</h2><span className="muted">Ledger verified</span></div><div className="claim-history"><div className="history-item"><span className="history-icon">🧧</span><div><strong>Claim a Telegram envelope</strong><small>Tap a claim button in a group to see it here</small></div><span className="muted">—</span></div></div></section></main>;
}
